DEFAULT
CUSTOM














Taiwan
Korea






China (Wide)












India







FR_400V_60H_CRAE_11

China MV
China 2013



India Std.



















FR_400V_50H_SEI4_18

China 2018










FR_400V_VFR2019_19













PL_400V_PN549-1_19










DE_400V_4105_18
DE_400V_4110_18












































AS4777.2_AU_A
AS4777.2_AU_B
AS4777.2_AU_C
AS4777.2_NZ

PL_400V_PN549-2_19