Default
CUSTOM
Netherlands
Belgium
France LV
Spain
Italy LV/SPI
Greece
Austria
Germany (3P)
Denmark
England
Ireland
Israel
Australia
Singapore
Taiwan
Korea
USA_240V
USA_208V
Slovakia
Czech Republic
Portugal
Germany
Bulgary
Spain RD1699
Italy MV
China
Italy LV/no SPI
UK G59-2 240
France LV VFR2013
France LV VFR2014
UK G83-2
Thailand MEA
Thailand PEA
French Islands 50Hz
French Islands 60Hz
Turkey
Queensland
Brazil
Nordics
Switzerland
India